export const jsonItems = [
  {
    Brand: "Apple",
    Category: "Mobile Phones",
    Description:
      "* Available to qualified customers and requires 24-month installment loan when you select Citizens One or Apple Card Monthly Installments (ACMI) as payment type at checkout at Apple. iPhone activation required with AT&T, T-Mobile, or Verizon for purchases made with ACMI at an Apple Store. Subject to credit approval and credit limit. Taxes and shipping are not included in ACMI and are subject to your card’s variable APR. Additional Apple Card Monthly Installments terms are in the Apple Card Customer Agreement(Opens in a new window). Additional iPhone Payments terms are here(Opens in a new window). ACMI is not available for purchases made online at special storefronts. The last month’s payment for each product will be the product’s purchase price, less all other payments at the monthly payment amount.",
    Discount: 4000,
    ExpiryTime: null,
    Name: "iPhone 14 Pro",
    Offer: null,
    Price: 123000,
    createdAt: "06/11/2023 15:46",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FzisVpaeQ9JQTP4LPljqY?alt=media&token=605c7429-089f-412e-a923-1035278ce431",
    productNo: "10",
    "created time": "06/11/2023 15:46",
    "updated time": "06/11/2023 15:46",
  },
  {
    Brand: "Air Max",
    Category: "Shoe",
    Description:
      "Made from at least 20% recycled materials by weight, the Nike Air VaporMax 2021 Flyknit is airy, supportive and easy to wear—thanks to its seamless design and Flyknit fabric. The stitched-on Swoosh and plastic heel clip add a splash of intrigue as you float down the streets on incredibly soft cushioning.",
    Discount: 300,
    ExpiryTime: null,
    Name: "Air Max 90 ",
    Offer: null,
    Price: 5000,
    createdAt: "06/11/2023 19:38",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2Fz3bySvmmiIuT4mNNW8RI?alt=media&token=de2b56ae-8495-4044-911f-fe1a5c00414e",
    productNo: "9",
    "created time": "06/11/2023 19:38",
    "updated time": "06/12/2023 11:45",
  },
  {
    Brand: "Nike",
    Category: "Shoe",
    Description:
      "Inspired by the Nike Air Max 90, the Nike Air Max Excee is a celebration of a classic through a new lens. Elongated lines and distorted proportions on the upper bring the '90s look you love into a new, modern space.",
    Discount: 3000,
    ExpiryTime: null,
    Name: "Nike Air Max Excee",
    Offer: null,
    Price: 13999,
    createdAt: "06/11/2023 17:46",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FyEVDmpitsULIY03pPwEM?alt=media&token=93a26129-765d-494f-8c3b-b243da3faf87",
    productNo: "28",
    "created time": "06/11/2023 17:46",
    "updated time": "06/12/2023 11:45",
  },
  {
    Brand: "Air Jordan",
    Category: "Shoe",
    Description:
      "Made from at least 20% recycled materials by weight, the Nike Air VaporMax 2021 Flyknit is airy, supportive and easy to wear—thanks to its seamless design and Flyknit fabric. The stitched-on Swoosh and plastic heel clip add a splash of intrigue as you float down the streets on incredibly soft cushioning.",
    Discount: 3000,
    ExpiryTime: null,
    Name: "Nike Vapormax 2021 Flyknit",
    Offer: null,
    Price: 12000,
    createdAt: "06/11/2023 19:34",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2Fwl5afhPOqHKJNnShBBka?alt=media&token=fb04af6e-010f-4773-8ada-c9925fc1563c",
    productNo: "49",
    "created time": "06/11/2023 19:34",
    "updated time": "06/12/2023 11:45",
  },
  {
    Brand: "Apple",
    Category: "Mobile Phones",
    Description:
      "Note: Forbes Advisor may earn a commission on sales made from partner links on this page, but that doesn't affect our editors' opinions or evaluations. We offer information about investing and saving, but we do not offer any personal advice or recommendations. If you aren’t sure whether investing is right for you, or which investments are right for you, please consult an authorised financial adviser.",
    Discount: 10000,
    ExpiryTime: null,
    Name: "iphone 11 Pro",
    Offer: null,
    Price: 420000,
    createdAt: "06/11/2023 20:06",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FtPoNI4o79YbEplFThbOW?alt=media&token=ab4912c2-4f49-41be-b632-6e32393b90e2",
    productNo: 12,
    "created time": "06/11/2023 20:06",
    "updated time": "06/11/2023 20:06",
  },
  {
    Brand: "Air Max",
    Category: "Shoe",
    Description:
      "Made from at least 20% recycled materials by weight, the Nike Air VaporMax 2021 Flyknit is airy, supportive and easy to wear—thanks to its seamless design and Flyknit fabric. The stitched-on Swoosh and plastic heel clip add a splash of intrigue as you float down the streets on incredibly soft cushioning.",
    Discount: 400,
    ExpiryTime: null,
    Name: "Nike Air Max",
    Offer: null,
    Price: 6000,
    createdAt: "06/11/2023 19:37",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FrwFVdG9wDfdqWXA0TdwU?alt=media&token=be0e4e7b-b695-4911-ae1e-1f18aebe64a0",
    productNo: "39",
    "created time": "06/11/2023 19:37",
    "updated time": "06/12/2023 11:55",
  },
  {
    Brand: "Svmsung",
    Category: "Shoe",
    Description:
      "Note: Forbes Advisor may earn a commission on sales made from partner links on this page, but that doesn't affect our editors' opinions or evaluations. We offer information about investing and saving, but we do not offer any personal advice or recommendations. If you aren’t sure whether investing is right for you, or which investments are right for you, please consult an authorised financial adviser.",
    Discount: 3000,
    ExpiryTime: null,
    Name: "Samsung Galaxy S21",
    Offer: null,
    Price: 12000,
    createdAt: "06/11/2023 20:03",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FrfTCi5YiVIiQz0JCbdsp?alt=media&token=66ad7560-7636-4af5-9cac-66299473685f",
    productNo: "32",
    "created time": "06/11/2023 20:03",
    "updated time": "06/11/2023 20:03",
  },
  {
    Brand: "Nike",
    Category: "Shoe",
    Description:
      "Nike has developed a new shoe technology for both casual and every-day runners. Today, the sportswear giant is taking the wraps off of Joyride, a responsive cushioning system designed to adapt to individual foot strikes and offer high levels of impact absorption as your feet hit whatever surface you're running on. Nike says the idea with Joyride is to \"make running easy\" and give you more personalized comfort, which is made possible by thousands of tiny, energy-packed beads that form the shoe's midsole. You can get a great look at them in the Joyride Run Flyknit pictured above, the first Nike sneakers to feature the visible and colorful beads.",
    Discount: 1000,
    ExpiryTime: null,
    Name: "Nike's Joyride shoes ",
    Offer: null,
    Price: 6000,
    createdAt: "06/11/2023 17:47",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FgDVY5g4mDOJjU7twHIFp?alt=media&token=768ead25-9a2e-4744-b9e7-23eefe2953c1",
    productNo: "22",
    "created time": "06/11/2023 17:47",
    "updated time": "06/11/2023 17:47",
  },
  {
    Brand: "Apple",
    Category: "Laptop",
    Description:
      "M1 Max — the world’s most powerful chip for a pro notebook — builds on M1 Pro, taking its amazing capabilities even further. M1 Max features the same powerful 10-core CPU as M1 Pro, and doubles the GPU with up to a massive 32 cores for up to 4x faster GPU performance than M1. It also has up to 400GB/s of memory bandwidth — 2x that of M1 Pro and nearly 6x that of M1 — and up to 64GB of fast unified memory. With even the latest PC laptops topping out at 16GB of video memory, having this huge amount of memory available is game-changing for pro workloads, allowing pros to do things that were previously unimaginable on a notebook. 3D artists on the new MacBook Pro can now easily work with extreme geometry and textures in scenes that pro PC laptops can’t even run.1 M1 Max also offers an enhanced media engine that features two ProRes accelerators for even higher multi-stream performance. As a result, pros can edit up to 30 streams of 4K ProRes video or up to seven streams of 8K ProRes video in Final Cut Pro — more streams than on a 28-core Mac Pro with Afterburner. And for the first time on any Mac, video editors can grade color in HDR on 8K ProRes 4444 video on battery when they’re miles away from the edit bay.2",
    Discount: 80000,
    ExpiryTime: "July 8, 2023 04:55:00",
    Name: "Game-changing MacBook Pro with M1 Pro and M1 Max",
    Offer: "Yes",
    Price: 225000,
    createdAt: "06/11/2023 15:53",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FMSY3XbKxSAoQd0AmY3dy?alt=media&token=0ef787d3-dd99-4d3e-8649-078f7eb2d830",
    productNo: "18",
    updatedAt: "06/12/2023 17:37",
    "created time": "06/11/2023 15:53",
    "updated time": "06/12/2023 17:37",
  },
  {
    Brand: "Svmsung",
    Category: "Laptop",
    Description:
      "Moving on, both the PCs are available in Intel Core i5 or i7 12th-gen processors paired with Intel Iris X integrated graphics, 8GB to 32GB of LPDDR5 RAM depending upon the storage variant you pick. There’s a 63Wh battery under the hood on a 13.3” model while the larger 15.6” model gets a 68Wh battery so the battery life seems promising. You will get up to 65W fast charging tech onboard via USB-C. There’s a mic, headphone port, 2xUSB-C ports, and a single Thunderbolt 4 port for the Galaxy Book2 Pro 360.\n\nThe 13.3” Galaxy Book2 Pro, on the other hand, gets a microSD card, a Thunderbolt 4 port, a full-sized USB 3.2 port, a 1 USB-C port, a 3.5mm combo jack while the 15.6” gets SIM card slot and a full-sized HDMI port as well.",
    Discount: 2000,
    ExpiryTime: null,
    Name: "Samsung unveils Galaxy Book2 Pro Series Laptops at MWC 2022",
    Offer: null,
    Price: 74000,
    createdAt: "06/11/2023 18:26",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FIRgnQwfI9AhlcLol6xpr?alt=media&token=28c412a2-df99-4bea-9fa8-4bc6326bb4cb",
    productNo: "34",
    updatedAt: "06/11/2023 18:36",
    "created time": "06/11/2023 18:26",
    "updated time": "06/11/2023 18:36",
  },
  {
    Brand: "Acer",
    Category: "Laptop",
    Description:
      "If you’ve got cash to spend, the Razer Blade 17 is one of the fastest laptops you can buy right now. Its speed and its sleek, 17.3-inch anti-glare screen isn’t even the best part about this pick: it’s packed with features even professional gamers only ever dream of.\n\nFirst off, you’ve got a refresh rate as high as 360Hz — the highest refresh rate you can get in a laptop (note you can only get 360Hz on the FHD version). The display can be either full HD or even 4K if you’re willing to shell an extra few bucks and there’s NVIDIA GeForce RTX graphics for clear, immersive visuals on all your games.",
    Discount: 12000,
    ExpiryTime: null,
    Name: "Gear-Razer-blade-pro-17",
    Offer: null,
    Price: 248000,
    createdAt: "06/11/2023 17:54",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FIHoYeQ4xjzwCLae0xQma?alt=media&token=9aa183d8-f50c-4233-8c33-61710bf4da48",
    productNo: "0",
    updatedAt: "06/12/2023 12:27",
    "created time": "06/11/2023 17:54",
    "updated time": "06/12/2023 12:48",
  },
  {
    Brand: "Apple",
    Category: "Mobile Phones",
    Description:
      "Note: Forbes Advisor may earn a commission on sales made from partner links on this page, but that doesn't affect our editors' opinions or evaluations. We offer information about investing and saving, but we do not offer any personal advice or recommendations. If you aren’t sure whether investing is right for you, or which investments are right for you, please consult an authorised financial adviser.",
    Discount: 12300,
    ExpiryTime: null,
    Name: "iPlus - Apple",
    Offer: null,
    Price: 123000,
    createdAt: "06/11/2023 20:08",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FHLXAbZpTcEGDCqGl9mLU?alt=media&token=9c4ad0aa-2323-420d-9e95-0ad78b7e3742",
    productNo: "50",
    updatedAt: "06/11/2023 20:13",
    "created time": "06/11/2023 20:08",
    "updated time": "06/11/2023 20:13",
  },
  {
    Brand: "Air Max",
    Category: "Shoe",
    Description:
      "The iconic sports shoe brand has world-over renown and it’s nearly impossible to find anyone who doesn’t know Nike shoes as the famous swoosh logo makes them instantly recognizable. A favorite of athletes and everyday people alike, it’s the number-one athletic footwear brand in the world. The sneakers are known for their versatility, true-to-size fit, comfort, premium quality and outstanding performance. Available in many trendy styles – there’s sure to be one pair of Nike training shoes to suit your everyday look as well as contribute to the ultimate performance in sports. We carry everything from Nike basketball shoes to Nike training shoes, Nike shoes for tennis, cheerleading and so much more. The company has also grown to become an innovator of branding and advertising with its “Just Do It” tagline that was first introduced in 1987 and is still relevant today.",
    Discount: 500,
    ExpiryTime: null,
    Name: "NIKE MUST-HAVES FOR HER",
    Offer: null,
    Price: 3000,
    createdAt: "06/11/2023 16:36",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FHDb7RLK6MJACMvfrvNQN?alt=media&token=89598158-0d0a-4567-88db-b4f33df2e8ab",
    productNo: "50",
    updatedAt: "06/12/2023 11:57",
    "created time": "06/11/2023 16:36",
    "updated time": "06/12/2023 11:57",
  },
  {
    Brand: "Svmsung",
    Category: "Mobile Phones",
    Description:
      "Samsung Galaxy is a series of computing and mobile computing devices that are designed, manufactured and marketed by Samsung Electronics.",
    Discount: 30000,
    ExpiryTime: null,
    Name: "S21 Utra",
    Offer: null,
    Price: 110000,
    createdAt: "06/11/2023 16:56",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FCOAQ3e4S2E6I5i3mVqN4?alt=media&token=b37c9e66-c599-4c92-9044-56c5ca88036b",
    productNo: "12",
    "created time": "06/11/2023 16:56",
    "updated time": "06/11/2023 16:56",
  },
  {
    Brand: "Acer",
    Category: "Laptop",
    Description:
      "Dell, HP, Sony, and yeah…Acer. These four computer brands dominate the market. And you’re likely to come across the products when shopping for a new laptop. Since your laptop is an investment, you want your next laptop to be proven and tested.\n\nAcer produces remarkably good laptops and, as a discerning buyer, you might have a really tough time deciding which model to buy. The company’ product line caters to different segments. Whether you’re a student who needs a simple laptop to take lecture notes or an advanced gamer who needs a real beast for your gaming needs, Acer has something for you. We have done some some serious sleuthing and are happy to recommend these 6 best Acer laptops today.",
    Discount: 5000,
    ExpiryTime: null,
    Name: "Acer Swift Edge (SFA16-41)",
    Offer: null,
    Price: 60000,
    createdAt: "06/11/2023 17:57",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/dpshop254.appspot.com/o/products%2FAFsY4OV9yNaYV0JGoX4v?alt=media&token=a8316572-6aac-4483-9bbd-b4e254e62288",
    productNo: "11",
    updatedAt: "06/11/2023 18:38",
    "created time": "06/11/2023 17:57",
    "updated time": "06/12/2023 11:40",
  },
];
